sonar.projectKey=wilmarguarin_Company_Management_Platform_26de2f77-19c7-47e7-ad7e-9f2f8e37d9af
sonar.projectName=Company_Management_Platform
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/node_modules/**,**/static/**